//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BlitzDocs.Folder {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FolderServiceSoap", Namespace="http://www.blitzdocs.net/Folder.wsdl")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BlitzDataComponentProxy))]
    public partial class FolderService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddFolderAlertsUsingConfigurationOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateUsingConfigurationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFolderCreateFormOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFolderViewFormOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetByFolderReferenceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDocumentTypeListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDocumentsExOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertExOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCustomAttributeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomAttributesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDocumentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNotesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FolderService() {
            this.Url = global::BlitzDocs.Properties.Settings.Default.BlitzDocs_Folder_FolderService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddFolderAlertsUsingConfigurationCompletedEventHandler AddFolderAlertsUsingConfigurationCompleted;
        
        /// <remarks/>
        public event CreateUsingConfigurationCompletedEventHandler CreateUsingConfigurationCompleted;
        
        /// <remarks/>
        public event GetFolderCreateFormCompletedEventHandler GetFolderCreateFormCompleted;
        
        /// <remarks/>
        public event GetFolderViewFormCompletedEventHandler GetFolderViewFormCompleted;
        
        /// <remarks/>
        public event GetByFolderReferenceCompletedEventHandler GetByFolderReferenceCompleted;
        
        /// <remarks/>
        public event GetDocumentTypeListCompletedEventHandler GetDocumentTypeListCompleted;
        
        /// <remarks/>
        public event GetDocumentsExCompletedEventHandler GetDocumentsExCompleted;
        
        /// <remarks/>
        public event InsertExCompletedEventHandler InsertExCompleted;
        
        /// <remarks/>
        public event SearchCompletedEventHandler SearchCompleted;
        
        /// <remarks/>
        public event UpdateCustomAttributeCompletedEventHandler UpdateCustomAttributeCompleted;
        
        /// <remarks/>
        public event GetCustomAttributesCompletedEventHandler GetCustomAttributesCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event GetCompletedEventHandler GetCompleted;
        
        /// <remarks/>
        public event GetDocumentsCompletedEventHandler GetDocumentsCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event InsertCompletedEventHandler InsertCompleted;
        
        /// <remarks/>
        public event GetNotesCompletedEventHandler GetNotesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/Folder.wsdl/AddFolderAlertsUsingConfiguration", RequestNamespace="http://www.blitzdocs.net/Folder.wsdl", ResponseNamespace="http://www.blitzdocs.net/Folder.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FolderAlertProxy[] AddFolderAlertsUsingConfiguration(int folderId, short folderConfigurationId) {
            object[] results = this.Invoke("AddFolderAlertsUsingConfiguration", new object[] {
                        folderId,
                        folderConfigurationId});
            return ((FolderAlertProxy[])(results[0]));
        }
        
        /// <remarks/>
        public void AddFolderAlertsUsingConfigurationAsync(int folderId, short folderConfigurationId) {
            this.AddFolderAlertsUsingConfigurationAsync(folderId, folderConfigurationId, null);
        }
        
        /// <remarks/>
        public void AddFolderAlertsUsingConfigurationAsync(int folderId, short folderConfigurationId, object userState) {
            if ((this.AddFolderAlertsUsingConfigurationOperationCompleted == null)) {
                this.AddFolderAlertsUsingConfigurationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddFolderAlertsUsingConfigurationOperationCompleted);
            }
            this.InvokeAsync("AddFolderAlertsUsingConfiguration", new object[] {
                        folderId,
                        folderConfigurationId}, this.AddFolderAlertsUsingConfigurationOperationCompleted, userState);
        }
        
        private void OnAddFolderAlertsUsingConfigurationOperationCompleted(object arg) {
            if ((this.AddFolderAlertsUsingConfigurationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddFolderAlertsUsingConfigurationCompleted(this, new AddFolderAlertsUsingConfigurationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/Folder.wsdl/CreateUsingConfiguration", RequestNamespace="http://www.blitzdocs.net/Folder.wsdl", ResponseNamespace="http://www.blitzdocs.net/Folder.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FolderProxy CreateUsingConfiguration(short folderConfigurationId) {
            object[] results = this.Invoke("CreateUsingConfiguration", new object[] {
                        folderConfigurationId});
            return ((FolderProxy)(results[0]));
        }
        
        /// <remarks/>
        public void CreateUsingConfigurationAsync(short folderConfigurationId) {
            this.CreateUsingConfigurationAsync(folderConfigurationId, null);
        }
        
        /// <remarks/>
        public void CreateUsingConfigurationAsync(short folderConfigurationId, object userState) {
            if ((this.CreateUsingConfigurationOperationCompleted == null)) {
                this.CreateUsingConfigurationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateUsingConfigurationOperationCompleted);
            }
            this.InvokeAsync("CreateUsingConfiguration", new object[] {
                        folderConfigurationId}, this.CreateUsingConfigurationOperationCompleted, userState);
        }
        
        private void OnCreateUsingConfigurationOperationCompleted(object arg) {
            if ((this.CreateUsingConfigurationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateUsingConfigurationCompleted(this, new CreateUsingConfigurationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/Folder.wsdl/GetFolderCreateForm", RequestNamespace="http://www.blitzdocs.net/Folder.wsdl", ResponseNamespace="http://www.blitzdocs.net/Folder.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FolderCreateForm GetFolderCreateForm(short companyId, short sourceDataType, System.Guid impersonatedUserId, string receiptCookie) {
            object[] results = this.Invoke("GetFolderCreateForm", new object[] {
                        companyId,
                        sourceDataType,
                        impersonatedUserId,
                        receiptCookie});
            return ((FolderCreateForm)(results[0]));
        }
        
        /// <remarks/>
        public void GetFolderCreateFormAsync(short companyId, short sourceDataType, System.Guid impersonatedUserId, string receiptCookie) {
            this.GetFolderCreateFormAsync(companyId, sourceDataType, impersonatedUserId, receiptCookie, null);
        }
        
        /// <remarks/>
        public void GetFolderCreateFormAsync(short companyId, short sourceDataType, System.Guid impersonatedUserId, string receiptCookie, object userState) {
            if ((this.GetFolderCreateFormOperationCompleted == null)) {
                this.GetFolderCreateFormOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFolderCreateFormOperationCompleted);
            }
            this.InvokeAsync("GetFolderCreateForm", new object[] {
                        companyId,
                        sourceDataType,
                        impersonatedUserId,
                        receiptCookie}, this.GetFolderCreateFormOperationCompleted, userState);
        }
        
        private void OnGetFolderCreateFormOperationCompleted(object arg) {
            if ((this.GetFolderCreateFormCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFolderCreateFormCompleted(this, new GetFolderCreateFormCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/Folder.wsdl/GetFolderViewForm", RequestNamespace="http://www.blitzdocs.net/Folder.wsdl", ResponseNamespace="http://www.blitzdocs.net/Folder.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FolderCreateForm GetFolderViewForm(int folderId, string folderReferenceId, System.Guid impersonatedUserId) {
            object[] results = this.Invoke("GetFolderViewForm", new object[] {
                        folderId,
                        folderReferenceId,
                        impersonatedUserId});
            return ((FolderCreateForm)(results[0]));
        }
        
        /// <remarks/>
        public void GetFolderViewFormAsync(int folderId, string folderReferenceId, System.Guid impersonatedUserId) {
            this.GetFolderViewFormAsync(folderId, folderReferenceId, impersonatedUserId, null);
        }
        
        /// <remarks/>
        public void GetFolderViewFormAsync(int folderId, string folderReferenceId, System.Guid impersonatedUserId, object userState) {
            if ((this.GetFolderViewFormOperationCompleted == null)) {
                this.GetFolderViewFormOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFolderViewFormOperationCompleted);
            }
            this.InvokeAsync("GetFolderViewForm", new object[] {
                        folderId,
                        folderReferenceId,
                        impersonatedUserId}, this.GetFolderViewFormOperationCompleted, userState);
        }
        
        private void OnGetFolderViewFormOperationCompleted(object arg) {
            if ((this.GetFolderViewFormCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFolderViewFormCompleted(this, new GetFolderViewFormCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/Folder.wsdl/GetByFolderReference", RequestNamespace="http://www.blitzdocs.net/Folder.wsdl", ResponseNamespace="http://www.blitzdocs.net/Folder.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FolderProxy GetByFolderReference(string externalSystemId, string externalSystemFolderId) {
            object[] results = this.Invoke("GetByFolderReference", new object[] {
                        externalSystemId,
                        externalSystemFolderId});
            return ((FolderProxy)(results[0]));
        }
        
        /// <remarks/>
        public void GetByFolderReferenceAsync(string externalSystemId, string externalSystemFolderId) {
            this.GetByFolderReferenceAsync(externalSystemId, externalSystemFolderId, null);
        }
        
        /// <remarks/>
        public void GetByFolderReferenceAsync(string externalSystemId, string externalSystemFolderId, object userState) {
            if ((this.GetByFolderReferenceOperationCompleted == null)) {
                this.GetByFolderReferenceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByFolderReferenceOperationCompleted);
            }
            this.InvokeAsync("GetByFolderReference", new object[] {
                        externalSystemId,
                        externalSystemFolderId}, this.GetByFolderReferenceOperationCompleted, userState);
        }
        
        private void OnGetByFolderReferenceOperationCompleted(object arg) {
            if ((this.GetByFolderReferenceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByFolderReferenceCompleted(this, new GetByFolderReferenceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/Folder.wsdl/GetDocumentTypeList", RequestNamespace="http://www.blitzdocs.net/Folder.wsdl", ResponseNamespace="http://www.blitzdocs.net/Folder.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Group", IsNullable=false)]
        public FolderDocumentTypeListGroup[] GetDocumentTypeList(int folderId, bool filterByCreatable, bool organizeByStackingOrder, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.Guid> impersonatedUserId) {
            object[] results = this.Invoke("GetDocumentTypeList", new object[] {
                        folderId,
                        filterByCreatable,
                        organizeByStackingOrder,
                        impersonatedUserId});
            return ((FolderDocumentTypeListGroup[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDocumentTypeListAsync(int folderId, bool filterByCreatable, bool organizeByStackingOrder, System.Nullable<System.Guid> impersonatedUserId) {
            this.GetDocumentTypeListAsync(folderId, filterByCreatable, organizeByStackingOrder, impersonatedUserId, null);
        }
        
        /// <remarks/>
        public void GetDocumentTypeListAsync(int folderId, bool filterByCreatable, bool organizeByStackingOrder, System.Nullable<System.Guid> impersonatedUserId, object userState) {
            if ((this.GetDocumentTypeListOperationCompleted == null)) {
                this.GetDocumentTypeListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDocumentTypeListOperationCompleted);
            }
            this.InvokeAsync("GetDocumentTypeList", new object[] {
                        folderId,
                        filterByCreatable,
                        organizeByStackingOrder,
                        impersonatedUserId}, this.GetDocumentTypeListOperationCompleted, userState);
        }
        
        private void OnGetDocumentTypeListOperationCompleted(object arg) {
            if ((this.GetDocumentTypeListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDocumentTypeListCompleted(this, new GetDocumentTypeListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/Folder.wsdl/GetDocumentsEx", RequestNamespace="http://www.blitzdocs.net/Folder.wsdl", ResponseNamespace="http://www.blitzdocs.net/Folder.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Document", IsNullable=false)]
        public FolderDocumentsDocument[] GetDocumentsEx(int folderId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.Guid> impersonatedUserId) {
            object[] results = this.Invoke("GetDocumentsEx", new object[] {
                        folderId,
                        impersonatedUserId});
            return ((FolderDocumentsDocument[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDocumentsExAsync(int folderId, System.Nullable<System.Guid> impersonatedUserId) {
            this.GetDocumentsExAsync(folderId, impersonatedUserId, null);
        }
        
        /// <remarks/>
        public void GetDocumentsExAsync(int folderId, System.Nullable<System.Guid> impersonatedUserId, object userState) {
            if ((this.GetDocumentsExOperationCompleted == null)) {
                this.GetDocumentsExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDocumentsExOperationCompleted);
            }
            this.InvokeAsync("GetDocumentsEx", new object[] {
                        folderId,
                        impersonatedUserId}, this.GetDocumentsExOperationCompleted, userState);
        }
        
        private void OnGetDocumentsExOperationCompleted(object arg) {
            if ((this.GetDocumentsExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDocumentsExCompleted(this, new GetDocumentsExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/Folder.wsdl/InsertEx", RequestNamespace="http://www.blitzdocs.net/Folder.wsdl", ResponseNamespace="http://www.blitzdocs.net/Folder.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FolderProxy InsertEx(FolderProxy folderProxy, System.Guid impersonatedUserId, short folderConfigurationId) {
            object[] results = this.Invoke("InsertEx", new object[] {
                        folderProxy,
                        impersonatedUserId,
                        folderConfigurationId});
            return ((FolderProxy)(results[0]));
        }
        
        /// <remarks/>
        public void InsertExAsync(FolderProxy folderProxy, System.Guid impersonatedUserId, short folderConfigurationId) {
            this.InsertExAsync(folderProxy, impersonatedUserId, folderConfigurationId, null);
        }
        
        /// <remarks/>
        public void InsertExAsync(FolderProxy folderProxy, System.Guid impersonatedUserId, short folderConfigurationId, object userState) {
            if ((this.InsertExOperationCompleted == null)) {
                this.InsertExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertExOperationCompleted);
            }
            this.InvokeAsync("InsertEx", new object[] {
                        folderProxy,
                        impersonatedUserId,
                        folderConfigurationId}, this.InsertExOperationCompleted, userState);
        }
        
        private void OnInsertExOperationCompleted(object arg) {
            if ((this.InsertExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertExCompleted(this, new InsertExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/Folder.wsdl/Search", RequestNamespace="http://www.blitzdocs.net/Folder.wsdl", ResponseNamespace="http://www.blitzdocs.net/Folder.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FolderProxy[] Search(SearchValue[] searchValues) {
            object[] results = this.Invoke("Search", new object[] {
                        searchValues});
            return ((FolderProxy[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchAsync(SearchValue[] searchValues) {
            this.SearchAsync(searchValues, null);
        }
        
        /// <remarks/>
        public void SearchAsync(SearchValue[] searchValues, object userState) {
            if ((this.SearchOperationCompleted == null)) {
                this.SearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchOperationCompleted);
            }
            this.InvokeAsync("Search", new object[] {
                        searchValues}, this.SearchOperationCompleted, userState);
        }
        
        private void OnSearchOperationCompleted(object arg) {
            if ((this.SearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchCompleted(this, new SearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/Folder.wsdl/UpdateCustomAttribute", RequestNamespace="http://www.blitzdocs.net/Folder.wsdl", ResponseNamespace="http://www.blitzdocs.net/Folder.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateCustomAttribute(int folderId, sbyte attributeId, string newValue) {
            object[] results = this.Invoke("UpdateCustomAttribute", new object[] {
                        folderId,
                        attributeId,
                        newValue});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateCustomAttributeAsync(int folderId, sbyte attributeId, string newValue) {
            this.UpdateCustomAttributeAsync(folderId, attributeId, newValue, null);
        }
        
        /// <remarks/>
        public void UpdateCustomAttributeAsync(int folderId, sbyte attributeId, string newValue, object userState) {
            if ((this.UpdateCustomAttributeOperationCompleted == null)) {
                this.UpdateCustomAttributeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCustomAttributeOperationCompleted);
            }
            this.InvokeAsync("UpdateCustomAttribute", new object[] {
                        folderId,
                        attributeId,
                        newValue}, this.UpdateCustomAttributeOperationCompleted, userState);
        }
        
        private void OnUpdateCustomAttributeOperationCompleted(object arg) {
            if ((this.UpdateCustomAttributeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCustomAttributeCompleted(this, new UpdateCustomAttributeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/Folder.wsdl/GetCustomAttributes", RequestNamespace="http://www.blitzdocs.net/Folder.wsdl", ResponseNamespace="http://www.blitzdocs.net/Folder.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ExtendedAttribute[] GetCustomAttributes(FolderAttributeSetType attributeSetType, int folderId, System.Guid impersonatedUserId) {
            object[] results = this.Invoke("GetCustomAttributes", new object[] {
                        attributeSetType,
                        folderId,
                        impersonatedUserId});
            return ((ExtendedAttribute[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomAttributesAsync(FolderAttributeSetType attributeSetType, int folderId, System.Guid impersonatedUserId) {
            this.GetCustomAttributesAsync(attributeSetType, folderId, impersonatedUserId, null);
        }
        
        /// <remarks/>
        public void GetCustomAttributesAsync(FolderAttributeSetType attributeSetType, int folderId, System.Guid impersonatedUserId, object userState) {
            if ((this.GetCustomAttributesOperationCompleted == null)) {
                this.GetCustomAttributesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomAttributesOperationCompleted);
            }
            this.InvokeAsync("GetCustomAttributes", new object[] {
                        attributeSetType,
                        folderId,
                        impersonatedUserId}, this.GetCustomAttributesOperationCompleted, userState);
        }
        
        private void OnGetCustomAttributesOperationCompleted(object arg) {
            if ((this.GetCustomAttributesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomAttributesCompleted(this, new GetCustomAttributesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/Folder.wsdl/Create", RequestNamespace="http://www.blitzdocs.net/Folder.wsdl", ResponseNamespace="http://www.blitzdocs.net/Folder.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FolderProxy Create(short documentTypeListId) {
            object[] results = this.Invoke("Create", new object[] {
                        documentTypeListId});
            return ((FolderProxy)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(short documentTypeListId) {
            this.CreateAsync(documentTypeListId, null);
        }
        
        /// <remarks/>
        public void CreateAsync(short documentTypeListId, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        documentTypeListId}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/Folder.wsdl/Get", RequestNamespace="http://www.blitzdocs.net/Folder.wsdl", ResponseNamespace="http://www.blitzdocs.net/Folder.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FolderProxy Get(int id) {
            object[] results = this.Invoke("Get", new object[] {
                        id});
            return ((FolderProxy)(results[0]));
        }
        
        /// <remarks/>
        public void GetAsync(int id) {
            this.GetAsync(id, null);
        }
        
        /// <remarks/>
        public void GetAsync(int id, object userState) {
            if ((this.GetOperationCompleted == null)) {
                this.GetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOperationCompleted);
            }
            this.InvokeAsync("Get", new object[] {
                        id}, this.GetOperationCompleted, userState);
        }
        
        private void OnGetOperationCompleted(object arg) {
            if ((this.GetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompleted(this, new GetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/Folder.wsdl/GetDocuments", RequestNamespace="http://www.blitzdocs.net/Folder.wsdl", ResponseNamespace="http://www.blitzdocs.net/Folder.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FolderDocumentProxy[] GetDocuments(int id) {
            object[] results = this.Invoke("GetDocuments", new object[] {
                        id});
            return ((FolderDocumentProxy[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDocumentsAsync(int id) {
            this.GetDocumentsAsync(id, null);
        }
        
        /// <remarks/>
        public void GetDocumentsAsync(int id, object userState) {
            if ((this.GetDocumentsOperationCompleted == null)) {
                this.GetDocumentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDocumentsOperationCompleted);
            }
            this.InvokeAsync("GetDocuments", new object[] {
                        id}, this.GetDocumentsOperationCompleted, userState);
        }
        
        private void OnGetDocumentsOperationCompleted(object arg) {
            if ((this.GetDocumentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDocumentsCompleted(this, new GetDocumentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/Folder.wsdl/Update", RequestNamespace="http://www.blitzdocs.net/Folder.wsdl", ResponseNamespace="http://www.blitzdocs.net/Folder.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Update(FolderProxy folderProxy) {
            object[] results = this.Invoke("Update", new object[] {
                        folderProxy});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(FolderProxy folderProxy) {
            this.UpdateAsync(folderProxy, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(FolderProxy folderProxy, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        folderProxy}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/Folder.wsdl/Insert", RequestNamespace="http://www.blitzdocs.net/Folder.wsdl", ResponseNamespace="http://www.blitzdocs.net/Folder.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FolderProxy Insert(FolderProxy folderProxy) {
            object[] results = this.Invoke("Insert", new object[] {
                        folderProxy});
            return ((FolderProxy)(results[0]));
        }
        
        /// <remarks/>
        public void InsertAsync(FolderProxy folderProxy) {
            this.InsertAsync(folderProxy, null);
        }
        
        /// <remarks/>
        public void InsertAsync(FolderProxy folderProxy, object userState) {
            if ((this.InsertOperationCompleted == null)) {
                this.InsertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertOperationCompleted);
            }
            this.InvokeAsync("Insert", new object[] {
                        folderProxy}, this.InsertOperationCompleted, userState);
        }
        
        private void OnInsertOperationCompleted(object arg) {
            if ((this.InsertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertCompleted(this, new InsertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/Folder.wsdl/GetNotes", RequestNamespace="http://www.blitzdocs.net/Folder.wsdl", ResponseNamespace="http://www.blitzdocs.net/Folder.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FolderNoteProxy[] GetNotes(int id) {
            object[] results = this.Invoke("GetNotes", new object[] {
                        id});
            return ((FolderNoteProxy[])(results[0]));
        }
        
        /// <remarks/>
        public void GetNotesAsync(int id) {
            this.GetNotesAsync(id, null);
        }
        
        /// <remarks/>
        public void GetNotesAsync(int id, object userState) {
            if ((this.GetNotesOperationCompleted == null)) {
                this.GetNotesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNotesOperationCompleted);
            }
            this.InvokeAsync("GetNotes", new object[] {
                        id}, this.GetNotesOperationCompleted, userState);
        }
        
        private void OnGetNotesOperationCompleted(object arg) {
            if ((this.GetNotesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNotesCompleted(this, new GetNotesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/Folder.wsdl")]
    public partial class FolderAlertProxy : BlitzDocsComponentProxy {
        
        private System.Guid createdByUserIdField;
        
        private System.DateTime createdDateField;
        
        private AlertDeliveryType deliveryTypeField;
        
        private string descriptionField;
        
        private string emailAddressesField;
        
        private short emailRecipientIdField;
        
        private int folderIdField;
        
        private int idField;
        
        private bool isRecurrentField;
        
        private bool isTardySignalledField;
        
        private System.DateTime lastUpdateField;
        
        private System.DateTime tardyDateField;
        
        private int tardyTemplateIdField;
        
        private int templateIdField;
        
        private string urlField;
        
        /// <remarks/>
        public System.Guid CreatedByUserId {
            get {
                return this.createdByUserIdField;
            }
            set {
                this.createdByUserIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        public AlertDeliveryType DeliveryType {
            get {
                return this.deliveryTypeField;
            }
            set {
                this.deliveryTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddresses {
            get {
                return this.emailAddressesField;
            }
            set {
                this.emailAddressesField = value;
            }
        }
        
        /// <remarks/>
        public short EmailRecipientId {
            get {
                return this.emailRecipientIdField;
            }
            set {
                this.emailRecipientIdField = value;
            }
        }
        
        /// <remarks/>
        public int FolderId {
            get {
                return this.folderIdField;
            }
            set {
                this.folderIdField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public bool IsRecurrent {
            get {
                return this.isRecurrentField;
            }
            set {
                this.isRecurrentField = value;
            }
        }
        
        /// <remarks/>
        public bool IsTardySignalled {
            get {
                return this.isTardySignalledField;
            }
            set {
                this.isTardySignalledField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TardyDate {
            get {
                return this.tardyDateField;
            }
            set {
                this.tardyDateField = value;
            }
        }
        
        /// <remarks/>
        public int TardyTemplateId {
            get {
                return this.tardyTemplateIdField;
            }
            set {
                this.tardyTemplateIdField = value;
            }
        }
        
        /// <remarks/>
        public int TemplateId {
            get {
                return this.templateIdField;
            }
            set {
                this.templateIdField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/Folder.wsdl")]
    public enum AlertDeliveryType {
        
        /// <remarks/>
        NotSet,
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Email,
        
        /// <remarks/>
        HttpPost,
        
        /// <remarks/>
        WebService,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FolderNoteProxy))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FolderDocumentProxy))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FolderProxy))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FolderAlertProxy))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/Folder.wsdl")]
    public abstract partial class BlitzDocsComponentProxy : BlitzDataComponentProxy {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BlitzDocsComponentProxy))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FolderNoteProxy))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FolderDocumentProxy))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FolderProxy))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FolderAlertProxy))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/Folder.wsdl")]
    public abstract partial class BlitzDataComponentProxy {
        
        private DataStateType dataStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DataStateType DataState {
            get {
                return this.dataStateField;
            }
            set {
                this.dataStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/Folder.wsdl")]
    public enum DataStateType {
        
        /// <remarks/>
        Deleted,
        
        /// <remarks/>
        Detached,
        
        /// <remarks/>
        Modified,
        
        /// <remarks/>
        Unchanged,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/Folder.wsdl")]
    public partial class ValueListItem {
        
        private string valueField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/Folder.wsdl")]
    public partial class ValueList {
        
        private ValueListItem[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable=false)]
        public ValueListItem[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/Folder.wsdl")]
    public partial class ExtendedAttribute {
        
        private byte idField;
        
        private string descriptionField;
        
        private string dataTypeField;
        
        private bool requiredField;
        
        private bool requiredFieldSpecified;
        
        private string lookupListIDField;
        
        private string lookupListField;
        
        private string defaultValueField;
        
        private ValueList valueListField;
        
        /// <remarks/>
        public byte Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool Required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequiredSpecified {
            get {
                return this.requiredFieldSpecified;
            }
            set {
                this.requiredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string LookupListID {
            get {
                return this.lookupListIDField;
            }
            set {
                this.lookupListIDField = value;
            }
        }
        
        /// <remarks/>
        public string LookupList {
            get {
                return this.lookupListField;
            }
            set {
                this.lookupListField = value;
            }
        }
        
        /// <remarks/>
        public string DefaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
            }
        }
        
        /// <remarks/>
        public ValueList ValueList {
            get {
                return this.valueListField;
            }
            set {
                this.valueListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/Folder.wsdl")]
    public partial class SearchValue {
        
        private byte attributeIdField;
        
        private SearchValueOperators operatorField;
        
        private string valueField;
        
        private string[] valuesField;
        
        /// <remarks/>
        public byte AttributeId {
            get {
                return this.attributeIdField;
            }
            set {
                this.attributeIdField = value;
            }
        }
        
        /// <remarks/>
        public SearchValueOperators Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/Folder.wsdl")]
    public enum SearchValueOperators {
        
        /// <remarks/>
        Equals,
        
        /// <remarks/>
        DoesNotEqual,
        
        /// <remarks/>
        BeginsWith,
        
        /// <remarks/>
        EndsWith,
        
        /// <remarks/>
        Contains,
        
        /// <remarks/>
        GreaterThan,
        
        /// <remarks/>
        LessThan,
        
        /// <remarks/>
        GreaterThanOrEquals,
        
        /// <remarks/>
        LessThanOrEquals,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/Folder.wsdl")]
    public partial class FormItem {
        
        private string nameField;
        
        private string valueField;
        
        private string valueSourceField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string ValueSource {
            get {
                return this.valueSourceField;
            }
            set {
                this.valueSourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/Folder.wsdl")]
    public partial class FolderCreateForm {
        
        private string actionField;
        
        private string methodField;
        
        private FormItem[] formItemsField;
        
        /// <remarks/>
        public string Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        public string Method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        public FormItem[] FormItems {
            get {
                return this.formItemsField;
            }
            set {
                this.formItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/Folder.wsdl")]
    public partial class CustomAttribute {
        
        private byte idField;
        
        private string valueField;
        
        /// <remarks/>
        public byte Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/Folder.wsdl")]
    public partial class FolderNoteProxy : BlitzDocsComponentProxy {
        
        private string addedByLoginIdField;
        
        private System.Guid addedByUserIdField;
        
        private string contentField;
        
        private System.DateTime createdDateField;
        
        private string descriptionField;
        
        private int folderIdField;
        
        private int idField;
        
        private bool isDeletedField;
        
        private System.DateTime lastUpdateField;
        
        private int securityIdField;
        
        /// <remarks/>
        public string AddedByLoginId {
            get {
                return this.addedByLoginIdField;
            }
            set {
                this.addedByLoginIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid AddedByUserId {
            get {
                return this.addedByUserIdField;
            }
            set {
                this.addedByUserIdField = value;
            }
        }
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int FolderId {
            get {
                return this.folderIdField;
            }
            set {
                this.folderIdField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
            }
        }
        
        /// <remarks/>
        public int SecurityId {
            get {
                return this.securityIdField;
            }
            set {
                this.securityIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/Folder.wsdl")]
    public partial class FolderDocumentProxy : BlitzDocsComponentProxy {
        
        private string addedByLoginIdField;
        
        private System.Guid addedByUserIdField;
        
        private System.DateTime addedDateField;
        
        private string commentField;
        
        private int documentIdField;
        
        private short documentTypeIdField;
        
        private int folderIdField;
        
        private bool isDeletedField;
        
        private System.DateTime lastUpdateField;
        
        private int securityIdField;
        
        private short status1Field;
        
        private short status2Field;
        
        private string titleField;
        
        /// <remarks/>
        public string AddedByLoginId {
            get {
                return this.addedByLoginIdField;
            }
            set {
                this.addedByLoginIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid AddedByUserId {
            get {
                return this.addedByUserIdField;
            }
            set {
                this.addedByUserIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AddedDate {
            get {
                return this.addedDateField;
            }
            set {
                this.addedDateField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public int DocumentId {
            get {
                return this.documentIdField;
            }
            set {
                this.documentIdField = value;
            }
        }
        
        /// <remarks/>
        public short DocumentTypeId {
            get {
                return this.documentTypeIdField;
            }
            set {
                this.documentTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public int FolderId {
            get {
                return this.folderIdField;
            }
            set {
                this.folderIdField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
            }
        }
        
        /// <remarks/>
        public int SecurityId {
            get {
                return this.securityIdField;
            }
            set {
                this.securityIdField = value;
            }
        }
        
        /// <remarks/>
        public short Status1 {
            get {
                return this.status1Field;
            }
            set {
                this.status1Field = value;
            }
        }
        
        /// <remarks/>
        public short Status2 {
            get {
                return this.status2Field;
            }
            set {
                this.status2Field = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/Folder.wsdl")]
    public partial class FolderProxy : BlitzDocsComponentProxy {
        
        private short companyIdField;
        
        private string createdByLoginIdField;
        
        private System.Guid createdByUserIdField;
        
        private System.DateTime createdDateField;
        
        private int defaultDocumentSecurityIdField;
        
        private short documentTypeListIdField;
        
        private int idField;
        
        private bool isDeletedField;
        
        private System.DateTime lastUpdateField;
        
        private int securityIdField;
        
        private CustomAttribute[] customAttributesField;
        
        /// <remarks/>
        public short CompanyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        public string CreatedByLoginId {
            get {
                return this.createdByLoginIdField;
            }
            set {
                this.createdByLoginIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid CreatedByUserId {
            get {
                return this.createdByUserIdField;
            }
            set {
                this.createdByUserIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        public int DefaultDocumentSecurityId {
            get {
                return this.defaultDocumentSecurityIdField;
            }
            set {
                this.defaultDocumentSecurityIdField = value;
            }
        }
        
        /// <remarks/>
        public short DocumentTypeListId {
            get {
                return this.documentTypeListIdField;
            }
            set {
                this.documentTypeListIdField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
            }
        }
        
        /// <remarks/>
        public int SecurityId {
            get {
                return this.securityIdField;
            }
            set {
                this.securityIdField = value;
            }
        }
        
        /// <remarks/>
        public CustomAttribute[] CustomAttributes {
            get {
                return this.customAttributesField;
            }
            set {
                this.customAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.blitzdocs.net/Folder.wsdl")]
    public partial class FolderDocumentTypeListGroup {
        
        private string descriptionField;
        
        private short sortIndexField;
        
        private FolderDocumentTypeListGroupMember[] membersField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public short SortIndex {
            get {
                return this.sortIndexField;
            }
            set {
                this.sortIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Member", IsNullable=false)]
        public FolderDocumentTypeListGroupMember[] Members {
            get {
                return this.membersField;
            }
            set {
                this.membersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.blitzdocs.net/Folder.wsdl")]
    public partial class FolderDocumentTypeListGroupMember {
        
        private short documentTypeIdField;
        
        private string descriptionField;
        
        private short sortIndexField;
        
        /// <remarks/>
        public short DocumentTypeId {
            get {
                return this.documentTypeIdField;
            }
            set {
                this.documentTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public short SortIndex {
            get {
                return this.sortIndexField;
            }
            set {
                this.sortIndexField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.blitzdocs.net/Folder.wsdl")]
    public partial class FolderDocumentsDocument {
        
        private string addedByLoginIdField;
        
        private System.Guid addedByUserIdField;
        
        private System.DateTime addedDateField;
        
        private string commentField;
        
        private string contentTypeExtensionField;
        
        private short contentTypeIdField;
        
        private int documentIdField;
        
        private short documentTypeIdField;
        
        private string isDeletedField;
        
        private short status1Field;
        
        private short status2Field;
        
        private string titleField;
        
        /// <remarks/>
        public string AddedByLoginId {
            get {
                return this.addedByLoginIdField;
            }
            set {
                this.addedByLoginIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid AddedByUserId {
            get {
                return this.addedByUserIdField;
            }
            set {
                this.addedByUserIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AddedDate {
            get {
                return this.addedDateField;
            }
            set {
                this.addedDateField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public string ContentTypeExtension {
            get {
                return this.contentTypeExtensionField;
            }
            set {
                this.contentTypeExtensionField = value;
            }
        }
        
        /// <remarks/>
        public short ContentTypeId {
            get {
                return this.contentTypeIdField;
            }
            set {
                this.contentTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public int DocumentId {
            get {
                return this.documentIdField;
            }
            set {
                this.documentIdField = value;
            }
        }
        
        /// <remarks/>
        public short DocumentTypeId {
            get {
                return this.documentTypeIdField;
            }
            set {
                this.documentTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public string IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        public short Status1 {
            get {
                return this.status1Field;
            }
            set {
                this.status1Field = value;
            }
        }
        
        /// <remarks/>
        public short Status2 {
            get {
                return this.status2Field;
            }
            set {
                this.status2Field = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/Folder.wsdl")]
    public enum FolderAttributeSetType {
        
        /// <remarks/>
        CreateOrUpdate,
        
        /// <remarks/>
        Search,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void AddFolderAlertsUsingConfigurationCompletedEventHandler(object sender, AddFolderAlertsUsingConfigurationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddFolderAlertsUsingConfigurationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddFolderAlertsUsingConfigurationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FolderAlertProxy[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FolderAlertProxy[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CreateUsingConfigurationCompletedEventHandler(object sender, CreateUsingConfigurationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateUsingConfigurationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateUsingConfigurationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FolderProxy Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FolderProxy)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetFolderCreateFormCompletedEventHandler(object sender, GetFolderCreateFormCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFolderCreateFormCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFolderCreateFormCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FolderCreateForm Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FolderCreateForm)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetFolderViewFormCompletedEventHandler(object sender, GetFolderViewFormCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFolderViewFormCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFolderViewFormCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FolderCreateForm Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FolderCreateForm)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetByFolderReferenceCompletedEventHandler(object sender, GetByFolderReferenceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByFolderReferenceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByFolderReferenceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FolderProxy Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FolderProxy)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetDocumentTypeListCompletedEventHandler(object sender, GetDocumentTypeListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDocumentTypeListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDocumentTypeListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FolderDocumentTypeListGroup[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FolderDocumentTypeListGroup[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetDocumentsExCompletedEventHandler(object sender, GetDocumentsExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDocumentsExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDocumentsExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FolderDocumentsDocument[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FolderDocumentsDocument[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void InsertExCompletedEventHandler(object sender, InsertExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FolderProxy Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FolderProxy)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SearchCompletedEventHandler(object sender, SearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FolderProxy[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FolderProxy[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdateCustomAttributeCompletedEventHandler(object sender, UpdateCustomAttributeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCustomAttributeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCustomAttributeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetCustomAttributesCompletedEventHandler(object sender, GetCustomAttributesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomAttributesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomAttributesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExtendedAttribute[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExtendedAttribute[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FolderProxy Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FolderProxy)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetCompletedEventHandler(object sender, GetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FolderProxy Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FolderProxy)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetDocumentsCompletedEventHandler(object sender, GetDocumentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDocumentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDocumentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FolderDocumentProxy[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FolderDocumentProxy[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void InsertCompletedEventHandler(object sender, InsertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FolderProxy Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FolderProxy)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetNotesCompletedEventHandler(object sender, GetNotesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNotesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNotesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FolderNoteProxy[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FolderNoteProxy[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591