//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BlitzDocs.DocumentShareDocument {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DocumentShareDocumentServiceSoap", Namespace="http://www.blitzdocs.net/DocumentShareDocument.wsdl")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BlitzDataComponentProxy))]
    public partial class DocumentShareDocumentService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UpdateStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback AcceptAllPendingOperationCompleted;
        
        private System.Threading.SendOrPostCallback IndexFileForShareOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DocumentShareDocumentService() {
            this.Url = global::BlitzDocs.Properties.Settings.Default.BlitzDocs_DocumentShareDocument_DocumentShareDocumentService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UpdateStatusCompletedEventHandler UpdateStatusCompleted;
        
        /// <remarks/>
        public event RetrieveDocumentCompletedEventHandler RetrieveDocumentCompleted;
        
        /// <remarks/>
        public event AcceptAllPendingCompletedEventHandler AcceptAllPendingCompleted;
        
        /// <remarks/>
        public event IndexFileForShareCompletedEventHandler IndexFileForShareCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/DocumentShareDocument.wsdl/UpdateStatus", RequestNamespace="http://www.blitzdocs.net/DocumentShareDocument.wsdl", ResponseNamespace="http://www.blitzdocs.net/DocumentShareDocument.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DocumentShareDocumentProxy UpdateStatus(string documentShareId, int documentId, DocumentShareDocumentStatus status) {
            object[] results = this.Invoke("UpdateStatus", new object[] {
                        documentShareId,
                        documentId,
                        status});
            return ((DocumentShareDocumentProxy)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateStatusAsync(string documentShareId, int documentId, DocumentShareDocumentStatus status) {
            this.UpdateStatusAsync(documentShareId, documentId, status, null);
        }
        
        /// <remarks/>
        public void UpdateStatusAsync(string documentShareId, int documentId, DocumentShareDocumentStatus status, object userState) {
            if ((this.UpdateStatusOperationCompleted == null)) {
                this.UpdateStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateStatus", new object[] {
                        documentShareId,
                        documentId,
                        status}, this.UpdateStatusOperationCompleted, userState);
        }
        
        private void OnUpdateStatusOperationCompleted(object arg) {
            if ((this.UpdateStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateStatusCompleted(this, new UpdateStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/DocumentShareDocument.wsdl/RetrieveDocument", RequestNamespace="http://www.blitzdocs.net/DocumentShareDocument.wsdl", ResponseNamespace="http://www.blitzdocs.net/DocumentShareDocument.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RetrieveDocumentResult RetrieveDocument(string documentShareId, int documentId, short destinationDocumentTypeListId) {
            object[] results = this.Invoke("RetrieveDocument", new object[] {
                        documentShareId,
                        documentId,
                        destinationDocumentTypeListId});
            return ((RetrieveDocumentResult)(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveDocumentAsync(string documentShareId, int documentId, short destinationDocumentTypeListId) {
            this.RetrieveDocumentAsync(documentShareId, documentId, destinationDocumentTypeListId, null);
        }
        
        /// <remarks/>
        public void RetrieveDocumentAsync(string documentShareId, int documentId, short destinationDocumentTypeListId, object userState) {
            if ((this.RetrieveDocumentOperationCompleted == null)) {
                this.RetrieveDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveDocumentOperationCompleted);
            }
            this.InvokeAsync("RetrieveDocument", new object[] {
                        documentShareId,
                        documentId,
                        destinationDocumentTypeListId}, this.RetrieveDocumentOperationCompleted, userState);
        }
        
        private void OnRetrieveDocumentOperationCompleted(object arg) {
            if ((this.RetrieveDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveDocumentCompleted(this, new RetrieveDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/DocumentShareDocument.wsdl/AcceptAllPending", RequestNamespace="http://www.blitzdocs.net/DocumentShareDocument.wsdl", ResponseNamespace="http://www.blitzdocs.net/DocumentShareDocument.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DocumentShareDocumentProxy[] AcceptAllPending(string documentShareId) {
            object[] results = this.Invoke("AcceptAllPending", new object[] {
                        documentShareId});
            return ((DocumentShareDocumentProxy[])(results[0]));
        }
        
        /// <remarks/>
        public void AcceptAllPendingAsync(string documentShareId) {
            this.AcceptAllPendingAsync(documentShareId, null);
        }
        
        /// <remarks/>
        public void AcceptAllPendingAsync(string documentShareId, object userState) {
            if ((this.AcceptAllPendingOperationCompleted == null)) {
                this.AcceptAllPendingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAcceptAllPendingOperationCompleted);
            }
            this.InvokeAsync("AcceptAllPending", new object[] {
                        documentShareId}, this.AcceptAllPendingOperationCompleted, userState);
        }
        
        private void OnAcceptAllPendingOperationCompleted(object arg) {
            if ((this.AcceptAllPendingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AcceptAllPendingCompleted(this, new AcceptAllPendingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/DocumentShareDocument.wsdl/IndexFileForShare", RequestNamespace="http://www.blitzdocs.net/DocumentShareDocument.wsdl", ResponseNamespace="http://www.blitzdocs.net/DocumentShareDocument.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Guid IndexFileForShare(System.Guid documentShareId, short documentTypeId, string title, string comments, string fileContentType, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] documentContent) {
            object[] results = this.Invoke("IndexFileForShare", new object[] {
                        documentShareId,
                        documentTypeId,
                        title,
                        comments,
                        fileContentType,
                        documentContent});
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        public void IndexFileForShareAsync(System.Guid documentShareId, short documentTypeId, string title, string comments, string fileContentType, byte[] documentContent) {
            this.IndexFileForShareAsync(documentShareId, documentTypeId, title, comments, fileContentType, documentContent, null);
        }
        
        /// <remarks/>
        public void IndexFileForShareAsync(System.Guid documentShareId, short documentTypeId, string title, string comments, string fileContentType, byte[] documentContent, object userState) {
            if ((this.IndexFileForShareOperationCompleted == null)) {
                this.IndexFileForShareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIndexFileForShareOperationCompleted);
            }
            this.InvokeAsync("IndexFileForShare", new object[] {
                        documentShareId,
                        documentTypeId,
                        title,
                        comments,
                        fileContentType,
                        documentContent}, this.IndexFileForShareOperationCompleted, userState);
        }
        
        private void OnIndexFileForShareOperationCompleted(object arg) {
            if ((this.IndexFileForShareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IndexFileForShareCompleted(this, new IndexFileForShareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/DocumentShareDocument.wsdl")]
    public enum DocumentShareDocumentStatus {
        
        /// <remarks/>
        NotSet,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Rejected,
        
        /// <remarks/>
        Accepted,
        
        /// <remarks/>
        Shared,
        
        /// <remarks/>
        Delivered,
        
        /// <remarks/>
        Errored,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/DocumentShareDocument.wsdl")]
    public partial class DocumentShareDocumentProxy : BlitzDocsComponentProxy {
        
        private int attachmentDocumentIdField;
        
        private string commentsField;
        
        private System.DateTime dateAddedField;
        
        private System.DateTime dateDeliveredField;
        
        private DocumentShareDirection directionField;
        
        private int documentIdField;
        
        private System.Guid documentShareIdField;
        
        private short documentTypeIdField;
        
        private System.DateTime lastUpdateField;
        
        private DocumentShareDocumentStatus statusField;
        
        private string titleField;
        
        /// <remarks/>
        public int AttachmentDocumentId {
            get {
                return this.attachmentDocumentIdField;
            }
            set {
                this.attachmentDocumentIdField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateAdded {
            get {
                return this.dateAddedField;
            }
            set {
                this.dateAddedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateDelivered {
            get {
                return this.dateDeliveredField;
            }
            set {
                this.dateDeliveredField = value;
            }
        }
        
        /// <remarks/>
        public DocumentShareDirection Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        public int DocumentId {
            get {
                return this.documentIdField;
            }
            set {
                this.documentIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid DocumentShareId {
            get {
                return this.documentShareIdField;
            }
            set {
                this.documentShareIdField = value;
            }
        }
        
        /// <remarks/>
        public short DocumentTypeId {
            get {
                return this.documentTypeIdField;
            }
            set {
                this.documentTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
            }
        }
        
        /// <remarks/>
        public DocumentShareDocumentStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/DocumentShareDocument.wsdl")]
    public enum DocumentShareDirection {
        
        /// <remarks/>
        NotSet,
        
        /// <remarks/>
        SourceToDestination,
        
        /// <remarks/>
        DestinationToSource,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentShareDocumentProxy))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/DocumentShareDocument.wsdl")]
    public abstract partial class BlitzDocsComponentProxy : BlitzDataComponentProxy {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BlitzDocsComponentProxy))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentShareDocumentProxy))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/DocumentShareDocument.wsdl")]
    public abstract partial class BlitzDataComponentProxy {
        
        private DataStateType dataStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DataStateType DataState {
            get {
                return this.dataStateField;
            }
            set {
                this.dataStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/DocumentShareDocument.wsdl")]
    public enum DataStateType {
        
        /// <remarks/>
        Deleted,
        
        /// <remarks/>
        Detached,
        
        /// <remarks/>
        Modified,
        
        /// <remarks/>
        Unchanged,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/DocumentShareDocument.wsdl")]
    public partial class RetrieveDocumentResult {
        
        private DocumentShareDocumentProxy documentField;
        
        private string contentMimeTypeField;
        
        private byte[] contentField;
        
        /// <remarks/>
        public DocumentShareDocumentProxy Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        public string ContentMimeType {
            get {
                return this.contentMimeTypeField;
            }
            set {
                this.contentMimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdateStatusCompletedEventHandler(object sender, UpdateStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DocumentShareDocumentProxy Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DocumentShareDocumentProxy)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RetrieveDocumentCompletedEventHandler(object sender, RetrieveDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetrieveDocumentResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetrieveDocumentResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void AcceptAllPendingCompletedEventHandler(object sender, AcceptAllPendingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AcceptAllPendingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AcceptAllPendingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DocumentShareDocumentProxy[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DocumentShareDocumentProxy[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void IndexFileForShareCompletedEventHandler(object sender, IndexFileForShareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IndexFileForShareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IndexFileForShareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Guid Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Guid)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591