//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BlitzDocs.FolderDocument {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FolderDocumentServiceSoap", Namespace="http://www.blitzdocs.net/FolderDocument.wsdl")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BlitzDataComponentProxy))]
    public partial class FolderDocumentService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDocumentDimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDocumentContentOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePropertiesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FolderDocumentService() {
            this.Url = global::BlitzDocs.Properties.Settings.Default.BlitzDocs_FolderDocument_FolderDocumentService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDocumentDimeCompletedEventHandler GetDocumentDimeCompleted;
        
        /// <remarks/>
        public event GetDocumentCompletedEventHandler GetDocumentCompleted;
        
        /// <remarks/>
        public event GetDocumentContentCompletedEventHandler GetDocumentContentCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        public event GetCompletedEventHandler GetCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdatePropertiesCompletedEventHandler UpdatePropertiesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/FolderDocument.wsdl/GetDocumentDime", RequestNamespace="http://www.blitzdocs.net/FolderDocument.wsdl", ResponseNamespace="http://www.blitzdocs.net/FolderDocument.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DocumentProxy GetDocumentDime(int folderId, int documentId) {
            object[] results = this.Invoke("GetDocumentDime", new object[] {
                        folderId,
                        documentId});
            return ((DocumentProxy)(results[0]));
        }
        
        /// <remarks/>
        public void GetDocumentDimeAsync(int folderId, int documentId) {
            this.GetDocumentDimeAsync(folderId, documentId, null);
        }
        
        /// <remarks/>
        public void GetDocumentDimeAsync(int folderId, int documentId, object userState) {
            if ((this.GetDocumentDimeOperationCompleted == null)) {
                this.GetDocumentDimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDocumentDimeOperationCompleted);
            }
            this.InvokeAsync("GetDocumentDime", new object[] {
                        folderId,
                        documentId}, this.GetDocumentDimeOperationCompleted, userState);
        }
        
        private void OnGetDocumentDimeOperationCompleted(object arg) {
            if ((this.GetDocumentDimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDocumentDimeCompleted(this, new GetDocumentDimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/FolderDocument.wsdl/GetDocument", RequestNamespace="http://www.blitzdocs.net/FolderDocument.wsdl", ResponseNamespace="http://www.blitzdocs.net/FolderDocument.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetDocumentResult GetDocument(int folderId, int documentId) {
            object[] results = this.Invoke("GetDocument", new object[] {
                        folderId,
                        documentId});
            return ((GetDocumentResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetDocumentAsync(int folderId, int documentId) {
            this.GetDocumentAsync(folderId, documentId, null);
        }
        
        /// <remarks/>
        public void GetDocumentAsync(int folderId, int documentId, object userState) {
            if ((this.GetDocumentOperationCompleted == null)) {
                this.GetDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDocumentOperationCompleted);
            }
            this.InvokeAsync("GetDocument", new object[] {
                        folderId,
                        documentId}, this.GetDocumentOperationCompleted, userState);
        }
        
        private void OnGetDocumentOperationCompleted(object arg) {
            if ((this.GetDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDocumentCompleted(this, new GetDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/FolderDocument.wsdl/GetDocumentContent", RequestNamespace="http://www.blitzdocs.net/FolderDocument.wsdl", ResponseNamespace="http://www.blitzdocs.net/FolderDocument.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetDocumentContent(int folderId, int documentId) {
            object[] results = this.Invoke("GetDocumentContent", new object[] {
                        folderId,
                        documentId});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDocumentContentAsync(int folderId, int documentId) {
            this.GetDocumentContentAsync(folderId, documentId, null);
        }
        
        /// <remarks/>
        public void GetDocumentContentAsync(int folderId, int documentId, object userState) {
            if ((this.GetDocumentContentOperationCompleted == null)) {
                this.GetDocumentContentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDocumentContentOperationCompleted);
            }
            this.InvokeAsync("GetDocumentContent", new object[] {
                        folderId,
                        documentId}, this.GetDocumentContentOperationCompleted, userState);
        }
        
        private void OnGetDocumentContentOperationCompleted(object arg) {
            if ((this.GetDocumentContentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDocumentContentCompleted(this, new GetDocumentContentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/FolderDocument.wsdl/Delete", RequestNamespace="http://www.blitzdocs.net/FolderDocument.wsdl", ResponseNamespace="http://www.blitzdocs.net/FolderDocument.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Delete(int folderId, int documentId) {
            object[] results = this.Invoke("Delete", new object[] {
                        folderId,
                        documentId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(int folderId, int documentId) {
            this.DeleteAsync(folderId, documentId, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(int folderId, int documentId, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        folderId,
                        documentId}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/FolderDocument.wsdl/Get", RequestNamespace="http://www.blitzdocs.net/FolderDocument.wsdl", ResponseNamespace="http://www.blitzdocs.net/FolderDocument.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FolderDocumentProxy Get(int folderId, int documentId) {
            object[] results = this.Invoke("Get", new object[] {
                        folderId,
                        documentId});
            return ((FolderDocumentProxy)(results[0]));
        }
        
        /// <remarks/>
        public void GetAsync(int folderId, int documentId) {
            this.GetAsync(folderId, documentId, null);
        }
        
        /// <remarks/>
        public void GetAsync(int folderId, int documentId, object userState) {
            if ((this.GetOperationCompleted == null)) {
                this.GetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOperationCompleted);
            }
            this.InvokeAsync("Get", new object[] {
                        folderId,
                        documentId}, this.GetOperationCompleted, userState);
        }
        
        private void OnGetOperationCompleted(object arg) {
            if ((this.GetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompleted(this, new GetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/FolderDocument.wsdl/Update", RequestNamespace="http://www.blitzdocs.net/FolderDocument.wsdl", ResponseNamespace="http://www.blitzdocs.net/FolderDocument.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Update(FolderDocumentProxy folderDocumentProxy) {
            object[] results = this.Invoke("Update", new object[] {
                        folderDocumentProxy});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(FolderDocumentProxy folderDocumentProxy) {
            this.UpdateAsync(folderDocumentProxy, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(FolderDocumentProxy folderDocumentProxy, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        folderDocumentProxy}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.blitzdocs.net/FolderDocument.wsdl/UpdateProperties", RequestNamespace="http://www.blitzdocs.net/FolderDocument.wsdl", ResponseNamespace="http://www.blitzdocs.net/FolderDocument.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateProperties(int folderId, int documentId, short documentTypeId, string title, string comment, int securityId, short status1, short status2, bool isDeleted) {
            object[] results = this.Invoke("UpdateProperties", new object[] {
                        folderId,
                        documentId,
                        documentTypeId,
                        title,
                        comment,
                        securityId,
                        status1,
                        status2,
                        isDeleted});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePropertiesAsync(int folderId, int documentId, short documentTypeId, string title, string comment, int securityId, short status1, short status2, bool isDeleted) {
            this.UpdatePropertiesAsync(folderId, documentId, documentTypeId, title, comment, securityId, status1, status2, isDeleted, null);
        }
        
        /// <remarks/>
        public void UpdatePropertiesAsync(int folderId, int documentId, short documentTypeId, string title, string comment, int securityId, short status1, short status2, bool isDeleted, object userState) {
            if ((this.UpdatePropertiesOperationCompleted == null)) {
                this.UpdatePropertiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePropertiesOperationCompleted);
            }
            this.InvokeAsync("UpdateProperties", new object[] {
                        folderId,
                        documentId,
                        documentTypeId,
                        title,
                        comment,
                        securityId,
                        status1,
                        status2,
                        isDeleted}, this.UpdatePropertiesOperationCompleted, userState);
        }
        
        private void OnUpdatePropertiesOperationCompleted(object arg) {
            if ((this.UpdatePropertiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePropertiesCompleted(this, new UpdatePropertiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/FolderDocument.wsdl")]
    public partial class DocumentProxy : BlitzDocsComponentProxy {
        
        private short contentTypeIdField;
        
        private string createdByLoginIdField;
        
        private System.Guid createdByUserIdField;
        
        private System.DateTime createdDateField;
        
        private int fileSizeField;
        
        private bool isBlitzDocsPdfField;
        
        private bool isLockedForEditField;
        
        private bool isLockedForViewField;
        
        private bool isLockedForPrintField;
        
        private bool isInvalidPdfField;
        
        private bool isUnlockedPdfField;
        
        private bool hasPageImagesCreatedField;
        
        private int idField;
        
        private System.DateTime lastUpdateField;
        
        private short pageCountField;
        
        private DocumentSourceType sourceTypeField;
        
        private PrimaryDocumentStorageStatus storageStatusField;
        
        private short storageVolumeIdField;
        
        /// <remarks/>
        public short ContentTypeId {
            get {
                return this.contentTypeIdField;
            }
            set {
                this.contentTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public string CreatedByLoginId {
            get {
                return this.createdByLoginIdField;
            }
            set {
                this.createdByLoginIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid CreatedByUserId {
            get {
                return this.createdByUserIdField;
            }
            set {
                this.createdByUserIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        public int FileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsBlitzDocsPdf {
            get {
                return this.isBlitzDocsPdfField;
            }
            set {
                this.isBlitzDocsPdfField = value;
            }
        }
        
        /// <remarks/>
        public bool IsLockedForEdit {
            get {
                return this.isLockedForEditField;
            }
            set {
                this.isLockedForEditField = value;
            }
        }
        
        /// <remarks/>
        public bool IsLockedForView {
            get {
                return this.isLockedForViewField;
            }
            set {
                this.isLockedForViewField = value;
            }
        }
        
        /// <remarks/>
        public bool IsLockedForPrint {
            get {
                return this.isLockedForPrintField;
            }
            set {
                this.isLockedForPrintField = value;
            }
        }
        
        /// <remarks/>
        public bool IsInvalidPdf {
            get {
                return this.isInvalidPdfField;
            }
            set {
                this.isInvalidPdfField = value;
            }
        }
        
        /// <remarks/>
        public bool IsUnlockedPdf {
            get {
                return this.isUnlockedPdfField;
            }
            set {
                this.isUnlockedPdfField = value;
            }
        }
        
        /// <remarks/>
        public bool HasPageImagesCreated {
            get {
                return this.hasPageImagesCreatedField;
            }
            set {
                this.hasPageImagesCreatedField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
            }
        }
        
        /// <remarks/>
        public short PageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
            }
        }
        
        /// <remarks/>
        public DocumentSourceType SourceType {
            get {
                return this.sourceTypeField;
            }
            set {
                this.sourceTypeField = value;
            }
        }
        
        /// <remarks/>
        public PrimaryDocumentStorageStatus StorageStatus {
            get {
                return this.storageStatusField;
            }
            set {
                this.storageStatusField = value;
            }
        }
        
        /// <remarks/>
        public short StorageVolumeId {
            get {
                return this.storageVolumeIdField;
            }
            set {
                this.storageVolumeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/FolderDocument.wsdl")]
    public enum DocumentSourceType {
        
        /// <remarks/>
        NotSet,
        
        /// <remarks/>
        Fax,
        
        /// <remarks/>
        Scan,
        
        /// <remarks/>
        Upload,
        
        /// <remarks/>
        Indexed,
        
        /// <remarks/>
        Import,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/FolderDocument.wsdl")]
    public enum PrimaryDocumentStorageStatus {
        
        /// <remarks/>
        NotSet,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Completed,
        
        /// <remarks/>
        ToBeDeleted,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FolderDocumentProxy))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentProxy))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/FolderDocument.wsdl")]
    public abstract partial class BlitzDocsComponentProxy : BlitzDataComponentProxy {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BlitzDocsComponentProxy))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FolderDocumentProxy))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentProxy))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/FolderDocument.wsdl")]
    public abstract partial class BlitzDataComponentProxy {
        
        private DataStateType dataStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DataStateType DataState {
            get {
                return this.dataStateField;
            }
            set {
                this.dataStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/FolderDocument.wsdl")]
    public enum DataStateType {
        
        /// <remarks/>
        Deleted,
        
        /// <remarks/>
        Detached,
        
        /// <remarks/>
        Modified,
        
        /// <remarks/>
        Unchanged,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/FolderDocument.wsdl")]
    public partial class GetDocumentResult {
        
        private DocumentProxy documentField;
        
        private byte[] contentField;
        
        /// <remarks/>
        public DocumentProxy Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.blitzdocs.net/FolderDocument.wsdl")]
    public partial class FolderDocumentProxy : BlitzDocsComponentProxy {
        
        private string addedByLoginIdField;
        
        private System.Guid addedByUserIdField;
        
        private System.DateTime addedDateField;
        
        private string commentField;
        
        private int documentIdField;
        
        private short documentTypeIdField;
        
        private int folderIdField;
        
        private bool isDeletedField;
        
        private System.DateTime lastUpdateField;
        
        private int securityIdField;
        
        private short status1Field;
        
        private short status2Field;
        
        private string titleField;
        
        /// <remarks/>
        public string AddedByLoginId {
            get {
                return this.addedByLoginIdField;
            }
            set {
                this.addedByLoginIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid AddedByUserId {
            get {
                return this.addedByUserIdField;
            }
            set {
                this.addedByUserIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AddedDate {
            get {
                return this.addedDateField;
            }
            set {
                this.addedDateField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public int DocumentId {
            get {
                return this.documentIdField;
            }
            set {
                this.documentIdField = value;
            }
        }
        
        /// <remarks/>
        public short DocumentTypeId {
            get {
                return this.documentTypeIdField;
            }
            set {
                this.documentTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public int FolderId {
            get {
                return this.folderIdField;
            }
            set {
                this.folderIdField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
            }
        }
        
        /// <remarks/>
        public int SecurityId {
            get {
                return this.securityIdField;
            }
            set {
                this.securityIdField = value;
            }
        }
        
        /// <remarks/>
        public short Status1 {
            get {
                return this.status1Field;
            }
            set {
                this.status1Field = value;
            }
        }
        
        /// <remarks/>
        public short Status2 {
            get {
                return this.status2Field;
            }
            set {
                this.status2Field = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetDocumentDimeCompletedEventHandler(object sender, GetDocumentDimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDocumentDimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDocumentDimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DocumentProxy Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DocumentProxy)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetDocumentCompletedEventHandler(object sender, GetDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetDocumentResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetDocumentResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetDocumentContentCompletedEventHandler(object sender, GetDocumentContentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDocumentContentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDocumentContentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetCompletedEventHandler(object sender, GetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FolderDocumentProxy Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FolderDocumentProxy)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdatePropertiesCompletedEventHandler(object sender, UpdatePropertiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePropertiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePropertiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591